package fi.fta.geoviite.infra.common

enum class MeasurementMethod {
    VERIFIED_DESIGNED_GEOMETRY,
    OFFICIALLY_MEASURED_GEODETICALLY,
    TRACK_INSPECTION,
    DIGITIZED_AERIAL_IMAGE,
    UNVERIFIED_DESIGNED_GEOMETRY,
    POINT_CLOUD_SIGNALED,
    POINT_CLOUD_UNSIGNALED,
    GNSS_IMU,
    RTK_GNSS,
}
