geoviite:
  scheduling:
    enabled: false
  cache:
    enabled: true
    preload: true
  data:
    import: false
  jwt:
    validation:
      enabled: false
  ratko:
    enabled: false
  projektivelho:
    enabled: false
  integration-api:
    enabled: true
    url-path-prefixes:
      - /rata-vkm
