geoviite:
  scheduling:
    enabled: true

  cache:
    enabled: true
    tasks:
      preload:
        enabled: true
        geocoding-contexts: true
        plan-headers: false

  data:
    import: false

  data-products:
    tasks:
      create-element-listing-csv:
        enabled: false

      create-vertical-geometry-listing-csv:
        enabled: false

      publication-geometry-remarks-update:
        enabled: false

  jwt:
    validation:
      enabled: false

  ratko:
    enabled: false

  # There is no need to generate any kind of OIDs in ext-api, but either Ratko or fake OID generator must be enabled.
  ratko-fake-oid-generator:
    enabled: true

  projektivelho:
    enabled: false

  ext-api:
    enabled: true
    max-batch-requests: 1000
    url-path-prefixes:
      - /geoviite
      - /rata-vkm
    public-hosts: "${GEOVIITE_EXT_API_PUBLIC_HOSTS:localhost}"
    private-hosts: "${GEOVIITE_EXT_API_PRIVATE_HOSTS:localhost}"

springdoc:
  enable-default-api-docs: false
  trim-kotlin-indent: true
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
