geoviite:
  e2e:
    url: "${FRONT_END_URL:http://127.0.0.1:9000}"
    username: foobar
    password: s3cret
  scheduler-lock:
    enabled: false
  projektivelho:
    enabled: true
    url: http://localhost:12346
    auth_url: http://localhost:12346/oauth2/token
    test-port: 12346
    client_id: foo
    secret_key: bar
