drop index if exists layout.segment_version_geometry_alignment_version_ix;
create index segment_version_geometry_alignment_version_ix on layout.segment_version (geometry_alignment_id, alignment_version);
