insert into common.location_track_owner(name)
  values
    ('Alva-Yhtiöt'),
    ('BE Group Oy'),
    ('Binderholz Nordic Oy'),
    ('Boliden Harjavalta Oy'),
    ('CT Logistics Oy'),
    ('Enocell Oy'),
    ('Enso Publication Papers'),
    ('Etelä-Pohjanmaan Voima Oy'),
    ('Eurohuolinta Oy'),
    ('Fingrid Oyj'),
    ('Haapamäen Museoveturiyhdistys ry'),
    ('HaminaKotka Satama Oy'),
    ('Haminan kaupunki'),
    ('Hangon kaupunki'),
    ('Hangon Satama Oy'),
    ('Helsingin Satama'),
    ('HTM Yhtiöt Oy'),
    ('Hyvinkään kaupunki'),
    ('Hämeenlinnan kaupunki'),
    ('Kaskisten kaupunki'),
    ('Keitele Timber Oy'),
    ('Keitele-Museo Oy'),
    ('Kemin satama'),
    ('Kemira Chemicals Oy'),
    ('Kiint. Oy Värtsilän Teollisuustie 5'),
    ('Kiinteistö Oy Pieksämäen Kangaskatu 26'),
    ('KIP Service Oy'),
    ('Kokkolan satama'),
    ('Kotkan kaupunki'),
    ('Kouvolan kaupunki'),
    ('Kuopion Energia'),
    ('Kuusakoski Oy'),
    ('Kvarken Ports Ltd'),
    ('Kymenso Oy'),
    ('Kymi Paper Oy'),
    ('Lappeenrannan kaupunki'),
    ('Loviisan kaupunki'),
    ('Loviisan Satama Oy'),
    ('Metsä Board Oyj'),
    ('Metsä Fibre Oy'),
    ('Metsä Fibre, Metsä Board'),
    ('Metsä Wood'),
    ('Meyer Turku Oy'),
    ('Momentive Specialty Chemicals'),
    ('Mondi Powerflute Oy'),
    ('Mondo Minerals BV'),
    ('Naantalin kaupunki'),
    ('Neste Oil Oyj'),
    ('Nordkalk Oy'),
    ('Norilsk Nickel Oy'),
    ('North European Oil Trade Oy'),
    ('Nurmeksen kunta'),
    ('Nurminen Logistics Oy'),
    ('Oulun kaupunki'),
    ('Oulun Satama Oy'),
    ('Outokumpu Stainless Oy'),
    ('Ovako Bar Oy Ab'),
    ('Oy Forcit Ab'),
    ('Oy Koneisto Ab'),
    ('Oy Teboil Ab'),
    ('Parma Consolis Iisalmi'),
    ('Pelkolan terminaali Oy'),
    ('Pietarsaaren satama Oy'),
    ('Porin satama'),
    ('Pyhäsalmi Mine Oy'),
    ('Raahen satama'),
    ('Raisio Oyj'),
    ('Raisiokaaren Teollisuuspuisto Oy'),
    ('Rauman satama'),
    ('Rautaruukki Oyj'),
    ('Riihimäen kaupunki'),
    ('Saimaan Satamat Oy'),
    ('Sappi Finland I Oy'),
    ('Scanpole Oy'),
    ('SkodaTranstech Oy'),
    ('Stora Enso Oyj'),
    ('Suomen Viljava Oy'),
    ('Taminco Finland Oy'),
    ('Tampereen kaupunki'),
    ('Terrafame Oy'),
    ('Turun Satama Oy'),
    ('UPM-Kymmene Oyj'),
    ('Uudenkaupungin kaupunki'),
    ('Uudenkaupungin Satama Oy'),
    ('Vaasan kaupunki'),
    ('Valkeakosken kaupunki'),
    ('Valmet Technologies Oy'),
    ('Valtra Oy'),
    ('Vapo Oy'),
    ('Varkauden kaupunki'),
    ('Versowood Oy'),
    ('Viking Malt Oy'),
    ('Walki Oy'),
    ('Yara Suomi Oy')
on conflict (name) do nothing;
