ALTER TYPE layout.location_track_naming_scheme RENAME VALUE 'WITHIN_OPERATING_POINT' TO 'WITHIN_OPERATIONAL_POINT';
ALTER TYPE layout.location_track_naming_scheme RENAME VALUE 'BETWEEN_OPERATING_POINTS' TO 'BETWEEN_OPERATIONAL_POINTS';
