-- TODO: move constraints here so they don't slow down the mass migration

-- TODO: These columns are no longer needed in the new model
-- alter table layout.location_track_version
--   drop column alignment_id,
--   drop column alignment_version,
--   drop column topology_start_switch_id,
--   drop column topology_start_switch_joint_number,
--   drop column topology_end_switch_id,
--   drop column topology_end_switch_joint_number;
-- alter table layout.location_track
--   drop column alignment_id,
--   drop column alignment_version,
--   drop column topology_start_switch_id,
--   drop column topology_start_switch_joint_number,
--   drop column topology_end_switch_id,
--   drop column topology_end_switch_joint_number;
