-- location tracks

alter table layout.location_track
  disable trigger version_update_trigger;
alter table layout.location_track
  disable trigger version_row_trigger;

create table layout.location_track_id
(
  id int not null primary key generated by default as identity
);
insert into layout.location_track_id (
  select distinct id
    from layout.location_track_version
);
select
  from (
    select
      nextval('layout.location_track_id_id_seq'),
      generate_series(1, (
        select max(id)
          from layout.location_track_id
      ))
  ) forward_ids;

alter table layout.location_track
  alter column layout_context_id drop expression, -- turn generated column into an ordinary column
  add constraint layout_context_id_check check (layout.layout_context_id(design_id, draft) = layout_context_id);

alter table layout.location_track
  drop constraint location_track_design_row_fk;
alter table layout.location_track
  drop constraint location_track_official_row_id_fkey;
alter table layout.location_track
  drop constraint location_track_official_id_fkey;

alter table layout.location_track
  drop constraint location_track_duplicate_of_location_track_id_fkey,
  add constraint location_track_duplicate_of_location_track_id_fkey foreign key (duplicate_of_location_track_id)
    references layout.location_track_id (id);

alter table publication.location_track
  drop constraint publication_location_track_location_track_fk,
  add constraint publication_location_track_location_track_fk foreign key (location_track_id)
    references layout.location_track_id (id);

alter table publication.switch_joint
  drop constraint publication_switch_joint_location_track_fk,
  add constraint publication_switch_joint_location_track_fk foreign key (location_track_id)
    references layout.location_track_id (id);

alter table integrations.ratko_push_error
  drop constraint ratko_push_error_location_track_id_fkey,
  add constraint ratko_push_error_location_track_id_fkey foreign key (location_track_id)
    references layout.location_track_id (id);

alter table publication.split
  disable trigger version_update_trigger;
alter table publication.split
  disable trigger version_row_trigger;

alter table publication.split
  add column layout_context_id text;
update publication.split
set layout_context_id = lt.layout_context_id
  from layout.location_track lt
  where split.source_location_track_row_id = lt.id and split.source_location_track_row_version = lt.version;
alter table publication.split
  alter column layout_context_id set not null;

alter table publication.split_version
  add column layout_context_id text;
update publication.split_version
set layout_context_id = lt.layout_context_id
  from layout.location_track lt
  where split_version.source_location_track_row_id = lt.id
    and split_version.source_location_track_row_version = lt.version;

alter table publication.split_version
  alter column layout_context_id set not null;

alter table publication.split
  enable trigger version_update_trigger;
alter table publication.split
  enable trigger version_row_trigger;


-- will be recreated later as this depends on layout.location_track's primary key
alter table publication.split
  drop constraint split_source_location_track_fkey;

alter table publication.split_target_location_track
  drop constraint split_target_location_track_fkey,
  add constraint split_target_location_track_fkey foreign key (location_track_id)
    references layout.location_track_id (id);

alter table publication.split_updated_duplicate
  drop constraint split_updated_duplicate_location_track_fkey,
  add constraint split_updated_duplicate_location_track_fkey foreign key (duplicate_location_track_id)
    references layout.location_track_id (id);

alter table publication.switch_joint
  drop constraint publication_switch_joint_location_track_fk,
  add constraint publication_switch_joint_location_track_fk foreign key (location_track_id)
    references layout.location_track_id (id);

-- will be recreated later, this is needed for publication.split to be able to lock down source location tracks
alter table layout.location_track
  drop constraint location_track_id_version_unique;

alter table layout.location_track
  alter column id drop identity;
alter table layout.location_track
  drop constraint location_track_pkey;

update layout.location_track
set id = official_id, version = last_version.version
  from layout.location_track_version last_version
  where location_track.official_id = last_version.id
    and location_track.layout_context_id = last_version.layout_context_id
    and not exists (
    select *
      from layout.location_track_version future_version
      where future_version.id = last_version.id
        and future_version.layout_context_id = last_version.layout_context_id
        and future_version.version > last_version.version
  );

alter table layout.location_track
  add constraint layout_location_track_pkey primary key (id, layout_context_id),
  -- excess constraint just for publication.split to have something to point to, as before
  add constraint location_track_id_version_unique unique (id, layout_context_id, version);

alter table publication.split
  rename column source_location_track_row_id to source_location_track_id;
alter table publication.split
  rename column source_location_track_row_version to source_location_track_version;

alter table publication.split_version
  rename column source_location_track_row_id to source_location_track_id;
alter table publication.split_version
  rename column source_location_track_row_version to source_location_track_version;

alter table publication.split
  add constraint split_source_location_track_fkey
    foreign key (source_location_track_id,
                 layout_context_id,
                 source_location_track_version)
      references layout.location_track (id, layout_context_id, version)
      deferrable initially deferred;

alter table layout.location_track
  add column origin_design_id int;
update layout.location_track
set origin_design_id = design_row.design_id
  from layout.location_track design_row
  where design_row.id = location_track.design_row_id;

alter table layout.location_track
  drop column official_id;
alter table layout.location_track
  drop column design_row_id;
alter table layout.location_track
  drop column official_row_id;

alter table layout.location_track
  add constraint location_track_id_fkey foreign key (id) references layout.location_track_id (id);

alter table layout.location_track
  enable trigger version_update_trigger;
alter table layout.location_track
  enable trigger version_row_trigger;

drop function layout.get_location_track_version(int);
select common.create_version_fetch_function('layout', 'location_track');
