-- track numbers

alter table layout.track_number
  disable trigger version_update_trigger;
alter table layout.track_number
  disable trigger version_row_trigger;

create table layout.track_number_id
(
  id int not null primary key generated by default as identity
);
insert into layout.track_number_id (
  select distinct id
    from layout.track_number_version
);
select
  from (
    select
      nextval('layout.track_number_id_id_seq'),
      generate_series(1, (
        select max(id)
          from layout.track_number_id
      ))
  ) forward_ids;

alter table layout.track_number
  alter column layout_context_id drop expression, -- turn generated column into an ordinary column
  add constraint layout_context_id_check check (layout.layout_context_id(design_id, draft) = layout_context_id);

-- objects referencing track numbers: All will reference the ID table instead
alter table layout.location_track
  drop constraint location_track_track_number_id_fkey,
  add constraint location_track_track_number_id_fkey
    foreign key (track_number_id) references layout.track_number_id (id);

alter table layout.km_post
  drop constraint km_post_track_number_id_fkey,
  add constraint km_post_track_number_id_fkey
    foreign key (track_number_id) references layout.track_number_id (id);

alter table layout.operating_point
  drop constraint operating_point_track_number_fk,
  add constraint operating_point_track_number_fk
    foreign key (track_number_id) references layout.track_number_id (id);

alter table layout.reference_line
  drop constraint reference_line_track_number_id_fkey,
  add constraint operating_point_track_number_fk
    foreign key (track_number_id) references layout.track_number_id (id);

alter table integrations.ratko_push_error
  drop constraint ratko_push_error_track_number_id_fkey,
  add constraint ratko_push_error_track_number_id_fkey
    foreign key (track_number_id) references layout.track_number_id (id);

alter table layout.track_number
  drop constraint track_number_official_id_fkey,
  add constraint track_number_official_id_fkey
    foreign key (id) references layout.track_number_id (id);

alter table publication.track_number
  drop constraint publication_track_number_track_number_fk,
  add constraint publication_track_number_track_number_fk
    foreign key (track_number_id) references layout.track_number_id (id);

alter table publication.switch_joint
  drop constraint publication_switch_joint_track_number_fk,
  add constraint publication_switch_joint_track_number_fk
    foreign key (track_number_id) references layout.track_number_id (id);

-- permanently removed constraints
alter table layout.track_number
  drop constraint track_number_design_row_fk;
alter table layout.track_number
  drop constraint track_number_official_row_id_fkey;

alter table layout.track_number
  alter column id drop identity;
alter table layout.track_number
  drop constraint track_number_pkey;

update layout.track_number
set id = official_id, version = last_version.version
  from layout.track_number_version last_version
  where track_number.official_id = last_version.id
    and track_number.layout_context_id = last_version.layout_context_id
    and not exists (
    select *
      from layout.track_number_version future_version
      where future_version.id = last_version.id
        and future_version.layout_context_id = last_version.layout_context_id
        and future_version.version > last_version.version
  );

alter table layout.track_number
  add constraint layout_track_number_pkey primary key (id, layout_context_id);

alter table layout.track_number
  add column origin_design_id int;
update layout.track_number
set origin_design_id = design_row.design_id
  from layout.track_number design_row
  where design_row.id = track_number.design_row_id;

alter table layout.track_number
  drop column official_id;
alter table layout.track_number
  drop column design_row_id;
alter table layout.track_number
  drop column official_row_id;

alter table layout.track_number
  enable trigger version_update_trigger;
alter table layout.track_number
  enable trigger version_row_trigger;

drop function layout.get_track_number_version(int);
select common.create_version_fetch_function('layout', 'track_number');
