-- reference lines

alter table layout.reference_line
  disable trigger version_update_trigger;
alter table layout.reference_line
  disable trigger version_row_trigger;

create table layout.reference_line_id
(
  id int not null primary key generated by default as identity
);
insert into layout.reference_line_id (
  select distinct id
    from layout.reference_line_version
);
select
  nextval('layout.reference_line_id_id_seq'),
  generate_series(1, (
    select max(id)
      from layout.reference_line_id
  ));

alter table layout.reference_line
  alter column layout_context_id drop expression, -- turn generated column into an ordinary column
  add constraint layout_context_id_check check (layout.layout_context_id(design_id, draft) = layout_context_id);

alter table layout.reference_line
  drop constraint reference_line_design_row_fk,
  drop constraint reference_line_official_row_id_fkey,
  drop constraint reference_line_official_id_fkey;

alter table publication.reference_line
  drop constraint publication_reference_line_reference_line_fk,
  add constraint publication_reference_line_reference_line_fk
    foreign key (reference_line_id) references layout.reference_line_id (id);

alter table layout.reference_line
  alter column id drop identity;
alter table layout.reference_line
  drop constraint reference_line_pkey;

update layout.reference_line
set id = official_id, version = last_version.version
  from layout.reference_line_version last_version
  where reference_line.official_id = last_version.id
    and reference_line.layout_context_id = last_version.layout_context_id
    and not exists (
    select *
      from layout.reference_line_version future_version
      where future_version.id = last_version.id
        and future_version.layout_context_id = last_version.layout_context_id
        and future_version.version > last_version.version
  );

alter table layout.reference_line
  add constraint layout_reference_line_pkey primary key (id, layout_context_id),
  add constraint layout_reference_line_id_fkey foreign key (id) references layout.reference_line_id (id);

alter table layout.reference_line
  add column origin_design_id int;
update layout.reference_line
set origin_design_id = design_row.design_id
  from layout.reference_line design_row
  where design_row.id = reference_line.design_row_id;

alter table layout.reference_line
  drop column official_id;
alter table layout.reference_line
  drop column design_row_id;
alter table layout.reference_line
  drop column official_row_id;

alter table layout.reference_line
  enable trigger version_update_trigger;
alter table layout.reference_line
  enable trigger version_row_trigger;

drop function layout.get_reference_line_version(int);
select common.create_version_fetch_function('layout', 'reference_line');
