create type common.location_accuracy as enum (
  'DESIGNED_GEOLOCATION',
  'OFFICIALLY_MEASURED_GEODETICALLY',
  'MEASURED_GEODETICALLY',
  'DIGITIZED_AERIAL_IMAGE',
  'GEOMETRY_CALCULATED'
  );

create type common.measurement_method as enum (
  'VERIFIED_DESIGNED_GEOMETRY',
  'OFFICIALLY_MEASURED_GEODETICALLY',
  'TRACK_INSPECTION',
  'DIGITIZED_AERIAL_IMAGE',
  'UNVERIFIED_DESIGNED_GEOMETRY'
)
