openapi: 3.1.0
info:
  title: Rata-VKM
  description: |
    Rataverkon viitekehysmuuntimella voi muuntaa koordinaatiston sijainteja rataosoitejärjestelmän sijainneiksi sekä toisin päin. Sijaintien muuntamiseen käytetään Geoviite-järjestelmän rataverkon tietoja. 

    Geoviitteen yhtenäisen rataverkon vastaavuutta maastoon rakennettuun rataverkkoon ei voida taata, joten viitekehysmuuntimen palauttamia tietoa ei tule käyttää suurta tarkkuutta vaativiin tehtäviin, esim. uusien suunnitelmien pohjatiedoksi.

    Ongelmatilanteessa ota yhteys ylläpitoon: geoviite.support@solita.fi
  version: 1.0.0

servers:
  - url: /rata-vkm

paths:
  /v1/rataosoitteet:
    get:
      summary: Yksittäismuunnos koordinaatista rataosoitteeseen
      description: >
        Palauttaa hakuehtoihin täsmäävän ja annettua koordinaattisijaintia lähinnä olevan raiteen ja rataosoitteen 
        raiteella. Mikäli annetuilla syötteillä ei löydy sijaintia, palauttaa virheen.
      parameters:
        - $ref: '#/components/parameters/koordinaatisto-param'
        - $ref: '#/components/parameters/x-koordinaatti-param'
        - $ref: '#/components/parameters/y-koordinaatti-param'
        - $ref: '#/components/parameters/sade-param'
        - $ref: '#/components/parameters/ratanumero-param'
        - $ref: '#/components/parameters/sijaintiraide-param'
        - $ref: '#/components/parameters/sijaintiraide_tyyppi-param'
        - $ref: '#/components/parameters/geometriatiedot-param'
        - $ref: '#/components/parameters/perustiedot-param'
        - $ref: '#/components/parameters/lisatiedot-param'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
              examples:
                'Onnistunut muunnos':
                  externalValue: '../static/examples/example-response-coordinate-to-track-address.json'
                'Virhe':
                  externalValue: '../static/examples/example-error-coordinate-to-track-address.json'
    post:
      summary: Erämuunnos koordinaateista rataosoitteisiin
      description: >
        Tämä toiminnallisuus on muutoin sama kuin yhden koordinaattisijainnin muuntaminen rataosoitteeksi, 
        mutta tässä toiminnossa voi yhdessä HTTP-pyynnössä välittää useampia muunnospyyntöjä kerrallaan. 
        Usean muunnospynnön suorittaminen kerralla on tehokkaampaa, kuin pyyntöjen suorittaminen erikseen. 
        Erämuunnos hyväksyy korkeintaan 1000 muunnospyyntöä kerrallaan. Erämuunnoksessa yleiset syötteet annetaan 
        URL-kyselyparametreina ja muunnospyyntökohtaiset syötteet HTTP-pyynnön sisältönä, JSON-muotoisena taulukkona.
      parameters:
        - $ref: '#/components/parameters/koordinaatisto-param'
        - $ref: '#/components/parameters/geometriatiedot-param'
        - $ref: '#/components/parameters/perustiedot-param'
        - $ref: '#/components/parameters/lisatiedot-param'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/coordinate-to-track-address'
            examples:
              'Muunnospyyntö':
                externalValue: '../static/examples/example-request-coordinate-to-track-address.json'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
              examples:
                'Onnistunut muunnos':
                  externalValue: '../static/examples/example-response-coordinate-to-track-address.json'
                'Virhe':
                  externalValue: '../static/examples/example-error-coordinate-to-track-address.json'


  /v1/koordinaatit:
    get:
      summary: Yksittäismuunnos rataosoitteesta koordinaatteihin
      description: >
        Palauttaa rataosoitetta vastaavat koordinaattisijainnit kaikille niille raiteille, joilla kyseinen 
        rataosoite on olemassa ja jotka täsmäävät muihin annettuihin hakuehtoihin. Mikäli yhtään sijaintia ei löydy, 
        palauttaa virheen.
      parameters:
        - $ref: '#/components/parameters/ratakilometri-param'
        - $ref: '#/components/parameters/ratametri-param'
        - $ref: '#/components/parameters/ratanumero-param-required'
        - $ref: '#/components/parameters/sijaintiraide-param'
        - $ref: '#/components/parameters/sijaintiraide_tyyppi-param'
        - $ref: '#/components/parameters/koordinaatisto-param'
        - $ref: '#/components/parameters/geometriatiedot-param'
        - $ref: '#/components/parameters/perustiedot-param'
        - $ref: '#/components/parameters/lisatiedot-param'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: '#/components/schemas/track-address-to-coordinate'
              examples:
                'Onnistunut muunnos':
                  externalValue: '../static/examples/example-response-track-address-to-coordinate.json'
                'Virhe':
                  externalValue: '../static/examples/example-error-track-address-to-coordinate.json'
    post:
      summary: Erämuunnos rataosoitteista koordinaatteihin
      description: >
        Tämä toiminnallisuus on muutoin sama kuin yhden rataosoitesijainnin muuntaminen koordinaattisijainneiksi, 
        mutta tässä toiminnossa voi yhdessä HTTP-pyynnössä välittää useampia muunnospyyntöjä kerrallaan. 
        Usean muunnospynnön suorittaminen kerralla on tehokkaampaa, kuin pyyntöjen suorittaminen erikseen. 
        Erämuunnos hyväksyy korkeintaan 1000 muunnospyyntöä kerrallaan. Erämuunnoksessa yleiset syötteet 
        annetaan URL-kyselyparametreina ja muunnospyyntökohtaiset syötteet HTTP-pyynnön sisältönä, 
        JSON-muotoisena taulukkona.
      parameters:
        - $ref: '#/components/parameters/koordinaatisto-param'
        - $ref: '#/components/parameters/geometriatiedot-param'
        - $ref: '#/components/parameters/perustiedot-param'
        - $ref: '#/components/parameters/lisatiedot-param'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/track-address-to-coordinate'
            examples:
              'Muunnospyyntö':
                externalValue: '../static/examples/example-request-track-address-to-coordinate.json'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
              examples:
                'Onnistunut muunnos':
                  externalValue: '../static/examples/example-response-track-address-to-coordinate.json'
                'Virhe':
                  externalValue: '../static/examples/example-error-track-address-to-coordinate.json'

components:
  schemas:
    tunniste:
      type: string
      description: 'Asettaa pyynnölle tunnisteen. Palautetaan GeoJSON-tuloksen properties-kentässä kaikille saman pyynnön tunnisteeseen liittyville muunnoksille.'
    koordinaatisto:
      type: string
      description: 'Asettaa koordinaatiston, jossa syöte- ja tuloskoordinaatit käsitellään (oletus ETRS-TM35FIN). Sallitut arvot ovat EPSG-tunnuksia.'
      default: EPSG:3067
    x:
      type: number
      description: 'x-koordinaatti'
    y:
      type: number
      description: 'y-koordinaatti'
    sade:
      type: integer
      description: 'Hakusäde metreissä annetusta koordinaatista.'
      default: 100
    ratanumero:
      type: string
      description: 'Rajaa haun ratanumeron nimen perusteella.'
    sijaintiraide:
      type: string
      description: 'Rajaa haun sijaintiraiteen nimen perusteella.'
    sijaintiraide_tyyppi:
      type: string
      description: 'Rajaa haun sijaintiraidetyypin perusteella. Sallitut arvot: "pääraide", "sivuraide", "turvaraide", "kujaraide".'
    ratakilometri:
      type: integer
      description: 'Rataosoitteen ratakilometri'
    ratametri:
      type: integer
      description: 'Rataosoitteen ratametri'

    track-address-to-coordinate:
      type: object
      required:
        - ratanumero
        - ratakilometri
        - ratametri
      properties:
        tunniste:
          $ref: '#/components/schemas/tunniste'
        ratanumero:
          $ref: '#/components/schemas/ratanumero'
        ratakilometri:
          $ref: '#/components/schemas/ratakilometri'
        ratametri:
          $ref: '#/components/schemas/ratametri'
        sijaintiraide:
          $ref: '#/components/schemas/sijaintiraide'
        sijaintiraide_tyyppi:
          $ref: '#/components/schemas/sijaintiraide_tyyppi'

    coordinate-to-track-address:
      type: object
      required:
        - x
        - y
      properties:
        tunniste:
          $ref: '#/components/schemas/tunniste'
        x:
          $ref: '#/components/schemas/x'
        y:
          $ref: '#/components/schemas/y'
        sade:
          $ref: '#/components/schemas/sade'
        ratanumero:
          $ref: '#/components/schemas/ratanumero'
        sijaintiraide:
          $ref: '#/components/schemas/sijaintiraide'
        sijaintiraide_tyyppi:
          $ref: '#/components/schemas/sijaintiraide_tyyppi'
  parameters:
    x-koordinaatti-param:
      name: x
      in: query
      required: true
      description: 'Koordinaatti X'
      schema:
        $ref: '#/components/schemas/x'
    y-koordinaatti-param:
      name: y
      in: query
      required: true
      description: 'Koordinaatti Y'
      schema:
        $ref: '#/components/schemas/y'
    koordinaatisto-param:
      name: koordinaatisto
      in: query
      required: false
      description: 'Koordinaatisto, jossa syöte- ja tuloskoordinaatit käsitellään (oletus EPSG:3067, eli ETRS-TM35FIN). Sallitut arvot ovat EPSG-tunnuksia, esim: EPSG:4326'
      schema:
        $ref: '#/components/schemas/koordinaatisto'
    sade-param:
      name: sade
      in: query
      required: false
      description: 'Hakusäde metreissä annetusta koordinaattisijainnista.'
      schema:
        $ref: '#/components/schemas/sade'
    ratanumero-param:
      name: ratanumero
      in: query
      required: false
      description: 'Rajaa haun ratanumeron nimen perusteella.'
      schema:
        $ref: '#/components/schemas/ratanumero'
    ratanumero-param-required:
      name: ratanumero
      in: query
      required: true
      description: 'Rajaa haun ratanumeron nimen perusteella.'
      schema:
        $ref: '#/components/schemas/ratanumero'
    sijaintiraide-param:
      name: sijaintiraide
      in: query
      required: false
      description: 'Rajaa haun sijaintiraiteen tunnuksen perusteella.'
      schema:
        $ref: '#/components/schemas/sijaintiraide'
    sijaintiraide_tyyppi-param:
      name: sijaintiraide_tyyppi
      in: query
      required: false
      description: 'Rajaa haun sijaintiraidetyypin perusteella. Sallitut arvot: "pääraide", "sivuraide", "turvaraide", "kujaraide".'
      schema:
        $ref: '#/components/schemas/sijaintiraide_tyyppi'
    ratakilometri-param:
      name: ratakilometri
      in: query
      required: true
      description: 'Rataosoitteen ratakilometri'
      schema:
        $ref: '#/components/schemas/ratakilometri'
    ratametri-param:
      name: ratametri
      in: query
      required: true
      description: 'Rataosoitteen ratametri'
      schema:
        $ref: '#/components/schemas/ratametri'
    geometriatiedot-param:
      name: geometriatiedot
      in: query
      required: false
      description: 'GeoJSON-tulos sisältää geometry-kentässä hakutuloksen geometriatiedot.'
      schema:
        type: boolean
        default: false
    perustiedot-param:
      name: perustiedot
      in: query
      required: false
      description: 'GeoJSON-tulos sisältää properties-kentässä x- ja y-koordinaatit sekä valimatka-kentän.'
      schema:
        type: boolean
        default: true
    lisatiedot-param:
      name: lisatiedot
      in: query
      required: false
      description: "GeoJSON-tulos sisältää properties-kentässä kentät: ratanumero, sijaintiraide, sijaintiraide_kuvaus, sijaintiraide_tyyppi, ratakilometri, ratametri, ratametri_desimaalit."
      schema:
        type: boolean
        default: true
