name: MAIN PULL REQUEST

run-name: ${{ github.actor }} wants to merge ${{ github.ref_name }}

on:
  pull_request:
    branches: [main]
    paths-ignore:
      - 'README.md'

jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
    - name: Download repository on the runner
      uses: actions/checkout@v3

    - name: Configure JDK 17 
      uses: actions/setup-java@v3
      with: 
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Execute Gradle build
      run: |
        cd infra
        ./gradlew build -x test 

    - name: run example unit test in infra (backend)
      run: |
        cd infra 
        gradle test --tests "fi.fta.geoviite.infra.linking.SuggestedSwitchTest"
