name: MAIN PULL REQUEST

run-name: ${{ github.actor }} wants to merge ${{ github.ref_name }}

on:
  pull_request:
    branches: [main]
    paths-ignore:
      - 'README.md'

jobs:
  runner-job:
    runs-on: ubuntu-latest

    steps:
    - name: Download repository on the runner
      uses: actions/checkout@v3

    - name: Configure JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Execute Gradle build
      run: |
        cd infra
        ./gradlew build -x test

    - name: run unit tests in infra (backend)
      run: |
        cd infra
        ./gradlew cleanTest test --tests "*Test"

    #KOKEILU!
    - name: Build docker image
      env:
        TEMURIN_IMAGE=eclipse-temurin:17-jdk
      run: |
        cd infra
        docker build -t gvt-db .

    - name: run integration tests in infra (backend)
      #env:
      #  DB_USERNAME: 'postgres'
      #  DB_PASSWORD: 'postgres'
      run: |
        cd infra
        docker run -p 5436:5432 gvt-db
        ./gradlew cleanTest test --tests "*IT"


      # Service container to run with `runner-job`
      #services:
      #  geoviite-postgres:
      #    image: 'gvt-db'
      #    env:
      #      POSTGRES_PASSWORD: 'postgres'
      #      POSTGRES_USER: 'postgres'
      #      POSTGRES_DB: 'geoviite'
      #    ports:
      #      - 127.0.0.1:5436:5432
