name: MAIN PULL REQUEST

run-name: ${{ github.actor }} wants to merge ${{ github.ref_name }}

on:
  pull_request:
    branches: [main]
    paths-ignore:
      - 'README.md'

jobs:
  runner-job:
    runs-on: ubuntu-latest

    steps:
    - name: Download repository on the runner
      uses: actions/checkout@v3

    - name: Configure JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Execute Gradle build
      run: |
        cd infra
        ./gradlew build -x test

    - name: run unit tests in infra (backend)
      run: |
        cd infra
        ./gradlew cleanTest test --tests "*Test"

    - name: run integration tests in infra (backend)
      run: |
        docker build -t gvt-postgres ./docker-images/geoviite-postgres
        docker run -d -p 127.0.0.1:5436:5432 -e POSTGRES_DB=$POSTGRES_DB -e POSTGRES_USER=$POSTGRES_USER -e POSTGRES_PASSWORD=$POSTGRES_PASSWORD --name geoviite-db gvt-postgres
        cd infra
        DB_NAME=geoviite DB_USER=dev-geouser DB_PASSWORD=dev-geouser-password ./gradlew cleanTest test --tests "*IT"
      env:
        POSTGRES_PASSWORD: 'dev-geouser-password'
        POSTGRES_USER: 'dev-geouser'
        POSTGRES_DB: 'geoviite'

    - name: Publish Test Report
      uses: mikepenz/action-junit-report@75b84e78b3f0aaea7ed7cf8d1d100d7f97f963ec
      if: success() || failure()
      with:
        report_paths: '**/build/test-results/test/*TEST.xml'
