name: MAIN PULL REQUEST

run-name: ${{ github.actor }} wants to merge ${{ github.ref_name }}

on:
  pull_request:
    branches: [main]
    paths-ignore:
      - 'README.md'

jobs:
  runner-job:
    runs-on: ubuntu-latest


    steps:
    - name: Download repository on the runner
      uses: actions/checkout@v3

    - name: Configure JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Execute Gradle build
      run: |
        cd infra
        ./gradlew build -x test

    - name: run unit tests in infra (backend)
      run: |
        cd infra
        ./gradlew cleanTest test --tests "*Test"

    - name: run integration tests in infra (backend)
      # env-muuttujat, toinen vaihtoehto: githubille oma application-yml? (tai käytä test-yml?)
      # https://stackoverflow.com/questions/59741629/how-to-pass-environment-variables-to-the-gradle-wrapper-build-using-only-command
      #unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /home/runner/work/geoviite/geoviite/Dockerfile: no such file or directory
      run: |
        docker build -t gvt-postgres ./.github/workflows
        docker create -p 127.0.0.1:5436:5432 --name geoviite-db gvt-postgres
        docker start geoviite-db
        timeout 20 ping 192.0.2.2
        cd infra
        DB_NAME=geoviite DB_USER=dev-geouser DB_PASSWORD=dev-geouser-password ./gradlew cleanTest test --tests "*IT"
      env:
        POSTGRES_PASSWORD: 'dev-geouser-password'
        POSTGRES_USER: 'dev-geouser'
        POSTGRES_DB: 'geoviite'

#POSTGRES_DB=geoviite POSTGRES_USER=dev-geouser POSTGRES_PASSWORD=dev-geouser-password
#--build-arg TEMURIN_IMAGE=eclipse-temurin:17-jdk
#services:
#  geoviite-postgres:
#    image: 'postgis/postgis:15-3.3-alpine'
#    env:
#      POSTGRES_PASSWORD: 'dev-geouser-password'
#      POSTGRES_USER: 'dev-geouser'
#      POSTGRES_DB: 'geoviite'
#      DB_NAME: 'geoviite'
#      DB_USER: 'dev-geouser'
#      DB_PASSWORD: 'dev-geouser-password'
#    ports:
#      - '127.0.0.1:5436:5432'
